GraphQLFormattedError: make locations, path opt'nl
See e.g. the flow definition in https://github.com/graphql/graphql-js/blob/master/src/error/formatError.js, where they are defined as optional.
I'm no GraphQL expert; caveat emptor.